FROM node:18-alpine

WORKDIR /usr/src/app

RUN apk update
RUN apk --no-cache add --virtual .builds-deps build-base python3
RUN apk --no-cache add bash
RUN apk --no-cache add libpq-dev

COPY package*.json ./

RUN npm install

COPY . .

RUN chmod +x ./wait-for-it.sh

CMD ["node", "-v"]
