'use strict';

module.exports = {
  UserService: require('./UserService'),
  BookService: require('./BookService'),
  AttachmentService: require('./AttachmentService'),
  StripeService: require('./StripeService'),
  PlanService: require('./PlanService'),
  SettingsService: require('./SettingsService'),
  SharingService: require('./SharingService'),
  BetaTestService: require('./BetaTestService'),
  TemplateService: require('./TemplateService'),
  CollaborationServiceV2: require('./CollaborationServiceV2'),
  ApplePayService: require('./ApplePayService'),
  TeamService: require('./TeamService'),
  ChatService: require('./ChatService'),
  SocketNotifyService: require('./SocketNotifyService'),
  AppVersionService: require('./AppVersionService'),
  TaskService: require('./TaskService'),
  CleanService: require('./CleanService'),
  CheckService: require('./CheckService'),
  SearchService: require('./SearchService'),
  NotificationService: require('./NotificationService'),
  StatisticService: require('./StatisticService'),
  DuplicationService: require('./DuplicationService'),
  GoogleCalendarService: require('./GoogleCalendarService'),
  PrivateChatService: require('./PrivateChatService'),
  ClientService: require('./ClientService'),
  FilterService: require('./FilterService'),
  ReactionsService: require('./ReactionsService'),
  FeatureFlagService: require('./FeatureFlagService'),
  ReminderService: require('./ReminderService')
};
