'use strict';

module.exports = {
  EMAIL_USED: 1,
  QUOTA_BOOKS: 2,
  QUOTA_PROJECTS: 3,
  QUOTA_SIZE: 4,
  USER_NAME_USED: 5,
  USER_DELETED: 6,
  VERIFICATION_CODE_INCORRECT: 7,
  VERIFICATION_CODE_EXPIRED: 8,
  QUOTA_MEMBERS: 9,
  QUOTA_CLIENTS: 10,
  QUOTA_TASKS: 11,
  QUOTA_SINGLE_SIZE: 12,
  SUBSCRIPTION_EXPIRED: 13
};
