module.exports = [
  'Your notes are automatically saved after every letter you type',
  'Invite as many observers as you want for free, observers can move tasks, complete tasks and comment.',
  'Drag and drop your spaces in the sidebar to reorganize them. ',
  'You can view your tasks in a board (Kanban), list or a calendar.',
  'You can create sections in the spaces page to organize your spaces in different categories.',
  'When you invite another members to your workspace, a chat functionality will appear in your sidebar menu. ',
  'You can use the ALT+C keyboard shortcut to quickly create a new task. ',
  'You can use the "@" symbol to nudge a member in your workspace. ',
  'You can use the "@" symbol to link to any other task or note.',
  'You can use the recently viewed icon in bottom-right corner to quickly jump to a task or note you previously viewed.',
  'You can change the letter type and page width of your notes in the page settings.',
  'In a task board, you can minimize task columns that you are not using (by clicking the minimize icon), this creates a less cluttered board.',
  'You can switch the way you view a task, you can either view them in a modal (default) or full-screen. ',
  'You can add a priority status to a task and subsequently group or filter your tasks on priority. ',
  'You can add cover images to your tasks which will show on a task card in the board overview. This creates a more visual task board. ',
  'You can add a lot of information to a task, the description field is similar to a note. You can add headers, emoji\'s, images, attachments and more. ',
  'You can decide what you want to show on a task using the filter menu. You don\'t want to see the subtitle? Simply hide it with one click. ',
  'You can change the icon of a space simply by clicking on it and selecting another icon. ',
  'You can 2-way sync your Google calendar with your Complex.so calendar, so everything is always up to date.',
  'Complex.so helps you to get more organized, become more productive and make you feel less stressed. ',
  'You can share your notes with anyone simply by copying the link and sharing it.',
  'You can embed YouTube videos in your notes by simply clicking the YouTube option in the toolbar.',
  'You can change the date format, first day of the week and the type of time you\'d like to use in settings ',
  'You can use CTRL+K to quickly search through your entire workspace.'
];
