'use strict';

module.exports = {
  // personal
  GOT_A_NEW_TASK: 1,
  MENTIONED_IN_CHAT: 2,
  MENTIONED_IN_PAGE: 4,
  MENTIONED_IN_COMMENT: 6,
  ADDED_TO_A_NEW_SPACE: 7,
  MENTIONED_IN_TASK: 8,
  ASSIGNED_TO_TASK: 9,
  TASK_DEADLINE: 13,
  BOOK_MEMBER_ADD: 14,
  BOOK_MEMBER_REMOVE: 15,
  ROLE_UPDATE: 16,
  HAS_BILLING_ACCESS: 17,
  NEW_PRIVATE_MESSAGE: 18,
  UNASSIGNED_FROM_TASK: 19,
  // general
  A_NEW_TEAM_MEMBER: 100,
  A_SPACE_HAS_BEEN_REMOVED: 101,
  A_NEW_PAGE_WAS_CREATED: 102,
  NEW_CHAT_MESSAGES: 104,
  A_SPACES_TITLE_WAS_CHANGED: 105,
  // book
  ACTIVE_TOOLS: 1000
};
